### ISSUE TITLE
The card stopped working after last update

### ISSUE THREAD

**Issue by niraviry** [robmarkoski/ha-clockwork-card#15]
Upgrading to 2023.12.1 caused the card to notify the card does not exists.
It is the only custom card that is not working.
No change in the code.

**Comment by ibz0q** [comment]
I was about to submit a PR and fix clockwork however with the most recent update it seems to be working fine.  

I created my own plugin last time clockwork broke which supports styling to clockworks style e.g. a lot more customization. I don't mean to spam this repo however I'm currently able to support my plugin if you face issues I believe this repo might be inactive.

<img src="https://github.com/robmarkoski/ha-clockwork-card/assets/81265647/54e5043f-a9a9-41c6-8200-899d4527b0e4" width="60%">

```Yaml
type: custom:better-moment-card
parentStyle: |
  line-height:normal;
  padding-bottom:0em;
  display: grid; 
  grid-template-columns: 1fr 1fr 1fr; 
  grid-template-rows: 1fr 1fr; 
  gap: 0px; 
  grid-template-areas: 
    'time time riyadh'
    'date date brussells'; 
moment:
  - format: HH:mm:ss
    style: |
      font-size:4.4em; 
      text-align:center; 
      font-weight:400; 
      grid-area: time;
      font-weight:500
  - format: dddd, DD MMMM
    style: |
      font-size:1.6em;
      line-height:1em; text-align:center;
      padding-top:0.5em;
      grid-area: date; 
  - format: HH:mm:ss
    timezone: Asia/Riyadh
    style: |
      text-align:center; 
      line-height:2em; 
      padding-top:0.2em; 
      grid-area: riyadh;
    template: |
      <strong>🇸🇦 Riyadh</strong>
      <div style="font-size:1.2em;">{{moment}}</div>
  - format: HH:mm:ss
    timezone: Europe/Brussels
    style: |
      text-align:center; 
      line-height:2em; 
      grid-area: brussells;
    template: |
      <strong>🇩🇪 Brussels</strong>
      <div style="font-size:1.2em;">{{moment}}</div>

```



https://github.com/ibz0q/better-moment-card
